# Generated by Django 5.0.3 on 2024-04-20 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('UserType', models.CharField(default='customer', max_length=100)),
                ('CompanyName', models.CharField(max_length=100, unique=True)),
                ('CompanyLocation', models.CharField(max_length=100)),
                ('GST_No', models.IntegerField()),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('Username', models.CharField(max_length=100, unique=True)),
                ('Password', models.CharField(max_length=100)),
                ('Mobile_No', models.CharField(max_length=20, unique=True)),
                ('Address', models.CharField(max_length=100)),
                ('Zipcode', models.IntegerField()),
            ],
        ),
    ]
