# Generated by Django 5.0.3 on 2024-04-26 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='UserId',
        ),
    ]
