# Generated by Django 5.0.3 on 2024-04-27 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_remove_contact_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='requestbook',
            fields=[
                ('RequestID', models.AutoField(primary_key=True, serialize=False)),
                ('ISBN_No', models.CharField(max_length=100)),
                ('BookTitle', models.CharField(max_length=100)),
                ('AuthorName', models.CharField(max_length=100)),
                ('Quantity', models.IntegerField()),
                ('EmailID', models.CharField(max_length=100)),
                ('Mobile_No', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='Email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='Location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='Mobile_No',
            field=models.CharField(max_length=20),
        ),
    ]
